import React from 'react'

const CustomTextfield = () => {
  return (
    <div className='bg-[#6B44E2]   rounded-xl mt-4'>
        <div className='bg-white h-[45px] w-full border-[1px] border-solid  border-[#6B44E2]  rounded-lg flex items-center gap-x-2 '>
            <input  type   className='pl-[15px] h-[43px] w-[90%]  rounded-lg focus:outline-none'
            placeholder='Type new questions'
            />
            <span class="material-symbols-outlined text-[#525354] cursor-pointerd cursor-pointer">
mic
</span>
<span class="material-symbols-outlined text-[#525354] cursor-pointer">
near_me
</span>
        </div>
            <p className='text-white py-1 text-[12px] text-center'>All the results are generated by AI, If you get any wrong answers report here</p>
    </div>
  )
}

export default CustomTextfield